- hosts: all
  vars:
    fw_op: present
  tasks:
  - debug: msg="{{ vars }}"
  - name: "Allow TCP on 80"
    pfsense_rule:
      name: 'Allow 80'
      action: pass
      interface: lan
      ipprotocol: inet
      protocol: tcp
      source: "{{ vm_ip_address }}"
      destination: any:80
      state: "{{ fw_op }}"

  - name: "Allow TCP on 443"
    pfsense_rule:
      name: 'Allow 443'
      action: pass
      interface: lan
      ipprotocol: inet
      protocol: tcp
      source: "{{ vm_ip_address }}"
      destination: any:443
      state: "{{ fw_op }}"

